services:
  aws:
    container_name: aws
    build: 
      context: .
    env_file: .env
    restart: always
    volumes:
      - ./bin:/app/bin
      - ./lib:/app/lib
      - ./test:/app/test
      - ./cdk.out:/app/cdk.out
      - ./scripts:/app/scripts
      # files
      - ./package.json:/app/package.json
      - ./cdk.json:/app/cdk.json
      - ./eslint.config.mjs:/app/eslint.config.mjs