Description: CloudFront Cache and Behavior Settings
Resources:
  pdfbuckerA0AC337E:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: pdf-bucket-5wyasda9
      ObjectLockEnabled: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: aws-cdk:cr-owned:0587f0e7
          Value: "true"
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: lab-14-stack/pdf-bucker/Resource
  pdfbuckerPolicyDAD5367A:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: pdfbuckerA0AC337E
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Condition:
              StringEquals:
                AWS:SourceArn:
                  Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":cloudfront::"
                      - Ref: AWS::AccountId
                      - :distribution/
                      - Ref: MyCloudfrontDistribution7D54D3CA
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - pdfbuckerA0AC337E
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: lab-14-stack/pdf-bucker/Policy/Resource
  jpgbucket78660766:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: jpg-bucket-5wyasda9
      ObjectLockEnabled: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: aws-cdk:cr-owned:567d16ae
          Value: "true"
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: lab-14-stack/jpg-bucket/Resource
  jpgbucketPolicy86D38EE4:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: jpgbucket78660766
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Condition:
              StringEquals:
                AWS:SourceArn:
                  Fn::Join:
                    - ""
                    - - "arn:"
                      - Ref: AWS::Partition
                      - ":cloudfront::"
                      - Ref: AWS::AccountId
                      - :distribution/
                      - Ref: MyCloudfrontDistribution7D54D3CA
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - jpgbucket78660766
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: lab-14-stack/jpg-bucket/Policy/Resource
  mystaticwebsitebucket48FB1B1C:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: my-static-website-5wyasda9
      ObjectLockEnabled: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: aws-cdk:cr-owned:1780d41c
          Value: "true"
      WebsiteConfiguration:
        IndexDocument: index.html
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: lab-14-stack/my-static-website-bucket/Resource
  mystaticwebsitebucketPolicyFCAD3424:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: mystaticwebsitebucket48FB1B1C
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              AWS: "*"
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - mystaticwebsitebucket48FB1B1C
                      - Arn
                  - /*
            Sid: Statement1
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: lab-14-stack/my-static-website-bucket/Policy/Resource
  DeployWebsiteAwsCliLayer17DBC421:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: cdk-hnb659fds-assets-266735829330-us-east-1
        S3Key: 1be473fb31b9ca92b2826d87592d6b342ab66fd93f4ba4e1a60e5920ced9e94c.zip
      Description: /opt/awscli/aws
    Metadata:
      aws:cdk:path: lab-14-stack/DeployWebsite/AwsCliLayer/Resource
      aws:asset:path: asset.1be473fb31b9ca92b2826d87592d6b342ab66fd93f4ba4e1a60e5920ced9e94c.zip
      aws:asset:is-bundled: false
      aws:asset:property: Content
  DeployWebsiteCustomResourceD116527B:
    Type: Custom::CDKBucketDeployment
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536
          - Arn
      SourceBucketNames:
        - cdk-hnb659fds-assets-266735829330-us-east-1
      SourceObjectKeys:
        - 4055a838b2f70f3761e4afc3985439a6ebdb298674360d00783c2d2ffda13a16.zip
      DestinationBucketName:
        Ref: mystaticwebsitebucket48FB1B1C
      Prune: true
      OutputObjectKeys: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: lab-14-stack/DeployWebsite/CustomResource/Default
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: lab-14-stack/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/Resource
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
            Effect: Allow
            Resource:
              - arn:aws:s3:::cdk-hnb659fds-assets-266735829330-us-east-1
              - arn:aws:s3:::cdk-hnb659fds-assets-266735829330-us-east-1/*
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - jpgbucket78660766
                  - Arn
              - Fn::GetAtt:
                  - mystaticwebsitebucket48FB1B1C
                  - Arn
              - Fn::GetAtt:
                  - pdfbuckerA0AC337E
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - jpgbucket78660766
                        - Arn
                    - /*
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - mystaticwebsitebucket48FB1B1C
                        - Arn
                    - /*
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - pdfbuckerA0AC337E
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF
      Roles:
        - Ref: CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
    Metadata:
      aws:cdk:path: lab-14-stack/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/DefaultPolicy/Resource
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-266735829330-us-east-1
        S3Key: c6358465bf49dfae556bb430bf9c81fa578c221b82c308e3707901b1dd654762.zip
      Environment:
        Variables:
          AWS_CA_BUNDLE: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
      Handler: index.handler
      Layers:
        - Ref: DeployWebsiteAwsCliLayer17DBC421
      Role:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
          - Arn
      Runtime: python3.11
      Timeout: 900
    DependsOn:
      - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF
      - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
    Metadata:
      aws:cdk:path: lab-14-stack/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/Resource
      aws:asset:path: asset.c6358465bf49dfae556bb430bf9c81fa578c221b82c308e3707901b1dd654762
      aws:asset:is-bundled: false
      aws:asset:property: Code
  DeployJpgAwsCliLayer75C75FD7:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: cdk-hnb659fds-assets-266735829330-us-east-1
        S3Key: 1be473fb31b9ca92b2826d87592d6b342ab66fd93f4ba4e1a60e5920ced9e94c.zip
      Description: /opt/awscli/aws
    Metadata:
      aws:cdk:path: lab-14-stack/DeployJpg/AwsCliLayer/Resource
      aws:asset:path: asset.1be473fb31b9ca92b2826d87592d6b342ab66fd93f4ba4e1a60e5920ced9e94c.zip
      aws:asset:is-bundled: false
      aws:asset:property: Content
  DeployJpgCustomResource1B9621B6:
    Type: Custom::CDKBucketDeployment
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536
          - Arn
      SourceBucketNames:
        - cdk-hnb659fds-assets-266735829330-us-east-1
      SourceObjectKeys:
        - 0942d916cb5423d29e985766030b714154fba70ec687b71c0ec4fbd1d5011a5f.zip
      DestinationBucketName:
        Ref: jpgbucket78660766
      Prune: true
      OutputObjectKeys: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: lab-14-stack/DeployJpg/CustomResource/Default
  DeployPdfAwsCliLayerD6B196CA:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: cdk-hnb659fds-assets-266735829330-us-east-1
        S3Key: 1be473fb31b9ca92b2826d87592d6b342ab66fd93f4ba4e1a60e5920ced9e94c.zip
      Description: /opt/awscli/aws
    Metadata:
      aws:cdk:path: lab-14-stack/DeployPdf/AwsCliLayer/Resource
      aws:asset:path: asset.1be473fb31b9ca92b2826d87592d6b342ab66fd93f4ba4e1a60e5920ced9e94c.zip
      aws:asset:is-bundled: false
      aws:asset:property: Content
  DeployPdfCustomResourceDB9509A9:
    Type: Custom::CDKBucketDeployment
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536
          - Arn
      SourceBucketNames:
        - cdk-hnb659fds-assets-266735829330-us-east-1
      SourceObjectKeys:
        - 70aa287ffe0934f73662d70622864574fad9f0ca479c7e36a8812891f8d4ce2e.zip
      DestinationBucketName:
        Ref: pdfbuckerA0AC337E
      Prune: true
      OutputObjectKeys: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: lab-14-stack/DeployPdf/CustomResource/Default
  MyOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: MyOAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
    Metadata:
      aws:cdk:path: lab-14-stack/MyOAC
  MyCloudfrontDistributionOrigin2S3OriginAccessControl4216DF4F:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: lab14MyCloudfrontDistributioOrigin2S3OriginAccessControl8B529F2B
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
    Metadata:
      aws:cdk:path: lab-14-stack/MyCloudfrontDistribution/Origin2/S3OriginAccessControl/Resource
  MyCloudfrontDistributionOrigin3S3OriginAccessControlB93EA90E:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: lab14MyCloudfrontDistributioOrigin3S3OriginAccessControlD35DEF72
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
    Metadata:
      aws:cdk:path: lab-14-stack/MyCloudfrontDistribution/Origin3/S3OriginAccessControl/Resource
  MyCloudfrontDistribution7D54D3CA:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CacheBehaviors:
          - CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            Compress: true
            PathPattern: "*.pdf"
            TargetOriginId: lab14stackMyCloudfrontDistributionOrigin27415C774
            ViewerProtocolPolicy: allow-all
          - CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            Compress: true
            PathPattern: "*.jpg"
            TargetOriginId: lab14stackMyCloudfrontDistributionOrigin34912EF5D
            ViewerProtocolPolicy: allow-all
        DefaultCacheBehavior:
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          Compress: true
          TargetOriginId: lab14stackMyCloudfrontDistributionOrigin1959A49C5
          ViewerProtocolPolicy: allow-all
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
              OriginSSLProtocols:
                - TLSv1.2
            DomainName:
              Fn::Select:
                - 2
                - Fn::Split:
                    - /
                    - Fn::GetAtt:
                        - mystaticwebsitebucket48FB1B1C
                        - WebsiteURL
            Id: lab14stackMyCloudfrontDistributionOrigin1959A49C5
          - DomainName:
              Fn::GetAtt:
                - pdfbuckerA0AC337E
                - RegionalDomainName
            Id: lab14stackMyCloudfrontDistributionOrigin27415C774
            OriginAccessControlId:
              Fn::GetAtt:
                - MyCloudfrontDistributionOrigin2S3OriginAccessControl4216DF4F
                - Id
            S3OriginConfig:
              OriginAccessIdentity: ""
          - DomainName:
              Fn::GetAtt:
                - jpgbucket78660766
                - RegionalDomainName
            Id: lab14stackMyCloudfrontDistributionOrigin34912EF5D
            OriginAccessControlId:
              Fn::GetAtt:
                - MyCloudfrontDistributionOrigin3S3OriginAccessControlB93EA90E
                - Id
            S3OriginConfig:
              OriginAccessIdentity: ""
    Metadata:
      aws:cdk:path: lab-14-stack/MyCloudfrontDistribution/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/+1W32/bOAz+W6bHQfV17T0MeUvT3lCg24J6uJfACGiJSdTIoqEfyXxG/veDbMt1t6EDtmGHAwoYkEVS+siPFKWL7M3b8+z8FRzdmZD7M63KrM09iD2Ho1u37jJrr4LYo1+1rOx+PkCFbMZeM87QCNvUXpFhM5Zfrt/PP8zf3VwzzkpNYr8MpVZiLgQ6N6yg8gGFvyOxvzFQapRstgHtMGk+Hg1at1M1m7Eet5PcmA1ZgZJxZrGiA+glaSUaNmMSnbfUsBN/cfDnHOTsiKVTHm+NxM/XJEKFxnewp4IvNqbfjvdDv3ysit6MPzudbNKvHra6Aoer4sTd5bqVWGtqInDWK69HAQfn0LtsHocT11CVErJ2sTF30KD9G61TZHiuzFajJ/NXMCIyu2pZCEoO/Olo69hsxV6zIibgoCyZMdJoEPddBluTS2nyqkIKycKSTooKK7JNrv4ZE1rvsEILOvdkYYsT1aEWj395KA36lNSN0uga57FKTtD2naVQD1NBMu2yAyM12uRKMNG3kW6Q8j16kOChD5F7G7D4tioyEDUv7Lyw80PsFHxyxr5Lzv+JiJup90/KAaS8m0bad7XEw4krqLL2njSuWgbOhQrlVcNmLautMkLVoOdCUBhZ6W3igrkY7oHoBavAwBZl1ygVRrT2iayZ28E2ufWJlgki9fZVO2i9B7G7NVoZHHVjRM8qn9/3v9B2hEfC+HAHRR5TGJ/oviusL6L7Wixl7sFjzLB7AvtbxV0sfRgnLjQFubFkfHerfbRqq0x/+S/IeEuaXyvnrSrDcOYkbiBof4U7OCiyscyoW5VKHsRuzGk7nd7KVGgHhUe0S0ueBD2+CkBrOp6B1tEGpFQREnSCctPT8ojf5yKKfw108RsQCp5ffoPr8dTHFE15P6W3x7preWs4OqFVNj+6hVZdb1hF/+JX8O6xknvYKrPli+A8VffoKFiBCWAESQo+tShO3JDE7MH9cbi4yN78mZ2/enBKnQ1dK7vvx38BW/MuasoLAAA=
    Metadata:
      aws:cdk:path: lab-14-stack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

